Update patch set 1
Patch Set 1:

DEBUG util.py:417:   --> Already installed : openstack-macros-2018.1.2-0.noarch
DEBUG util.py:417:  Error: Package: libvirt-python-3.2.0-3.el7_4.1.x86_64 (build)
DEBUG util.py:417:             Requires: libvirt.so.0(LIBVIRT_3.1.0)(64bit)
DEBUG util.py:417:  Error: Package: libvirt-python-3.2.0-3.el7_4.1.x86_64 (build)
DEBUG util.py:417:             Requires: libvirt.so.0(LIBVIRT_3.0.0)(64bit)

Patch-set: 1